#:include ui/elements.kv

<SpellingActivityScreen>:
    BoxLayout:
        orientation: "vertical"
        ThemedLabel:
            text: "Escribe la palabra"
        TextInput:
            id: response_input
            multiline: False
            disabled: True
        ThemedButton
            text: "Seguir"
            #size_hint: .9,.1
            #pos_hint: {"center_x": .5, "top": .8}
            on_press:
                root.submit(response_input.text)