#:include mspelling/ui/elements.kv

<SpellingActivityScreen>:
    ThemedLayout:
        orientation: "vertical"
        ThemedLabel:
            text: "Escribe la palabra"
        ThemedTextInput:
            id: response_input
            disabled: True
        ThemedButton:
            text: "Seguir"
            #size_hint: .9,.1
            #pos_hint: {"center_x": .5, "top": .8}
            on_press:
                root.submit(response_input.text)