@startuml Entities and Responsibilities
!theme spacelab

entity MSpellingApp {
    Basic config
    Starting app
}

entity SetupController {
    Choose appropriate screen
}

entity SetWorkspaceScreen {
    Present screen to choose dir 
    Go to appropriate screen
}

entity SetWorkspaceController {
}

entity LoginScreen {
    Collect participant id
    Pass participant id to handler
}

entity LoginController {
    Store participant id
}

entity BeginScreen {
    Present begin message
    Go to next screen
}

entity SpellingController {
    Setup everything
    Manage trial sequence 
    Provide access to data
    Provide access to stim
    Submit data
    Save data
}

entity TrialStimView {
    Presents stim cue
    Run present stim
}

entity TrialStimController {
    Setup stim 
    Present stim
    Validate stim
}

entity TrialResponseScreen {
    Cue participant for response 
    Collect response
    Pass response to handler
}

entity TrialResponseController {
    Submit response
    Continue trial sequence
}

entity RestScreen {
    Cue participant to rest 
}

entity RestController {
    Resume activity after an ISI
}

entity EndScreen {
    Present end message
}

entity StimController {   
    Interact with the AudioController 
    Interact with the stimuli package
    Prepare stim 
    Present the stim
}

entity AudioController {
    Play audio
    Setup audio device
    Validate audio file
}

entity Data {
    Interact with the data package 
    Manage the data 
    Add data
}

MSpellingApp --> LoadingView
LoadingView --> SetupController
SetupController --> SetWorkspaceScreen
SetupController --> LoginScreen
SetWorkspaceScreen --> SetWorkspaceController
SetWorkspaceController --> LoginScreen
LoginScreen --> LoginController
LoginController --> BeginScreen
BeginScreen --> SpellingController
SpellingController --> Data
SpellingController --> TrialStimView
TrialStimView --> TrialStimController
TrialStimController --> SpellingController
TrialStimController --> StimController
SpellingController --> TrialResponseScreen
TrialResponseScreen --> TrialResponseController
TrialResponseController --> SpellingController
SpellingController --> RestScreen
RestScreen --> RestController
RestController --> SpellingController
SpellingController --> EndScreen
SpellingController --> LoginController
SpellingController --> StimController
StimController --> AudioController
@enduml
