@startuml Entities and Responsibilities
!theme spacelab

entity MSpellingApp{
    Basic config
    Starting app
}

entity SetupController{
    Choose appropriate screen
}

entity SetWorkspaceScreen{
    Present screen to choose dir 
    Go to appropriate screen
}

entity SetWorkspaceController{
}

entity LoginScreen{
    Collect participant id
    Store participant id appropriately
}

entity LoginController{}

entity BeginScreen{
    Present begin message
    Go to next screen
}

entity SpellingController{
    Setup everything
    Manage trial sequence 
    Add data
    Prepare stim 
    Saves data
}

entity TrialStimView{
    Presents stim cue
    Run present stim
}

entity TrialStimController{
    Setup stim 
    Present stim
    Validate stim
}

entity TrialResponseScreen{
    Cue participant for response 
    Collect response
    Add trial data with other data
    ' Pass response
    Continues trial sequence
}

entity ResponseController{}

entity RestScreen{
    Cue participant to rest 
    Start again after an ISI
}

entity RestController{}

entity EndScreen{
    Present end message
}

entity Stim{}
entity Data{}

MSpellingApp --> SetupController
SetupController --> SetWorkspaceScreen
SetupController --> LoginScreen
SetWorkspaceScreen --> SetWorkspaceController
SetWorkspaceScreen --> SetupController 
LoginScreen --> LoginController
LoginScreen --> BeginScreen
BeginScreen --> SpellingController
SpellingController --> Stimuli
SpellingController --> Data
SpellingController --> TrialStimView
TrialStimView --> TrialStimController
TrialStimController --> SpellingController
TrialStimController --> Stim
SpellingController --> TrialResponseScreen
TrialResponseScreen --> ResponseController
TrialResponseScreen --> SpellingController
SpellingController --> RestScreen
RestScreen --> SpellingController
RestScreen --> RestController
SpellingController --> EndScreen
@enduml
