
name: Linting
on: [push, pull_request]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set up Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.7

      - name: Install nox
        run: |
          pip install nox==2021.6.12

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: false

      # - name: Run mypy with nox
      #   shell: bash
      #   run: nox --force-color -s mypy

      # - name: Run pre-commit hooks
      #   run: |
      #     pip install pre-commit
      #     pre-commit run --all-files
